# @package _group_

defaults:
  - audio: fbank
  - augment: default
  - dataset: librispeech
  - criterion: ctc
  - lr_scheduler: warmup
  - model: squeezeformer
  - trainer: gpu-fp16
  - trainer.logger: null
  - tokenizer: libri_subword
